baseURL = ""
languageCode = "en-us"
title = "Yan's Blog"
theme = "PaperMod"
ShowToc = true
TacOpen = true

paginate =10

[params.homeInfoParams]
Title ="Hey, I'm Yan \U0001F44B"
Content =  "Hey I'm a student majored in Computer Science and Mathmatics. Here I post some of my thoughts and notes."

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/Schroefelhof"

[[params.socialIcons]]
name = "instagram"
url = "https://www.instagram.com/yam8.rd"

#[[params.socialIcons]]
#name = "github"
#url = "https://github.com/guccimane44"

[params]
defaultTheme = "dark"
ShowReadingTime = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
#DisableScrollToTop = False
#hideFooter = False

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/archives/"
weight = 2

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 3

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 4

[[menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 5

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 6

[minify]
disableXML = true
